name: Deploy my portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Définir le nom de l'image
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/portfolio:latest

          # Construire l'image
          docker build -t $IMAGE_NAME .

          # Pousser l'image sur Docker Hub
          docker push $IMAGE_NAME

     
      - name: Install cURL
        run: sudo apt-get install -y curl

      
      - name: Create Vercel Project
        env:
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        run: |
          # Définir le nom du projet
          PROJECT_NAME=$(basename $(git rev-parse --show-toplevel))

          # Appeler l'API de création de projet
          RESPONSE=$(curl -X POST https://api.vercel.com/v9/projects \
            -H "Authorization: Bearer $VERCEL_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"name\": \"$PROJECT_NAME\",
              \"framework\": null,
              \"public\": true
            }")

          echo "Response: $RESPONSE"

     
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --confirm
