# name: Build and Deploy Docker Image

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker image
#         run: |
#           docker build -t elpidio16/my-portfolio:latest .

#       - name: Push Docker image
#         run: |
#           docker push elpidio16/my-portfolio:latest

#       - name: Deploy to Vercel
#         env:
#           VERCEL_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
#         run: |
#           npm install -g vercel
#           vercel --prod --token $VERCEL_TOKEN --confirm
