name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Changez cette branche si nécessaire

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer cURL
      - name: Install cURL
        run: sudo apt-get install -y curl

      # Étape 3 : Créer le projet sur Vercel via API
      - name: Create Vercel Project
        env:
          VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        run: |
          # Définir le nom du projet (nom du dépôt GitHub)
          PROJECT_NAME=$(basename $(git rev-parse --show-toplevel))

          # Appeler l'API de création de projet sans Team ID
          RESPONSE=$(curl -X POST https://api.vercel.com/v9/projects \
            -H "Authorization: Bearer $VERCEL_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"name\": \"$PROJECT_NAME\",
              \"framework\": null,
              \"public\": true
            }")

          echo "Response: $RESPONSE"

      # Étape 4 : Déployer avec Vercel CLI
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
        run: |
          npm install -g vercel
          vercel --prod --token $VERCEL_TOKEN --confirm
